# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('artist_id', models.ManyToManyField(to='movieApp.Artist')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Movie_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('is_active', models.IntegerField()),
                ('user_type', models.IntegerField()),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('last_login', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'movie_user',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.Movie_user'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_id',
            field=models.ManyToManyField(to='movieApp.Genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.Movie_user'),
        ),
        migrations.AddField(
            model_name='artist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.Movie_user'),
        ),
    ]
