# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_id',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
