# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_auto_20190828_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='movieImage/'),
        ),
    ]
