# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_user',
            name='first_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie_user',
            name='last_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
