# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0007_auto_20190828_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_user',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
