# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-29 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0009_remove_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
